/*	Example Interrupt Handlers
 *	Copyright (c) 2020 by SECKC Software
 */
#include <stdint.h>
#include "gpio_def.h"
#include "interrupt.h"

/* Generated by the following python script:
import math
for t in xrange(0,256):
	print int(128+127 * math.sin(t * 2 * math.pi / 256 )),",",
*/
static const uint8_t wavetable[]=
{
#include "wavetable.csv"
};

static const uint8_t dither_me_timbers[]=
{
0 , 1 , 1 , 1 , 1 , 0 , 1 , 1 , 1 , 1 , 0 , 1 , 1 , 0 , 1 , 0 , 1 , 0 , 1 , 0 , 1 , 0 , 0 , 1 , 0 , 0 , 0 , 0 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 1 , 0 , 0 , 0 , 0 , 1 , 0 , 0 , 1 , 0 , 1 , 0 , 1 , 0 , 1 , 0 , 1 , 1 , 0 , 1 , 1 , 1 , 1 , 0 , 1 , 1 , 1
};

unsigned char iterator;

@interrupt void ei0_interrupt(void)
{
iterator++;
if( iterator >= sizeof( dither_me_timbers ) )
	{
	iterator = 0;
	}

if( dither_me_timbers[iterator] )
	{
	GPIO_SET( GPIO_CC1050_DI_PORT, GPIO_CC1050_DI_PIN );
	}
else
	{
	GPIO_CLR( GPIO_CC1050_DI_PORT, GPIO_CC1050_DI_PIN );
	}
}